version: 2
jobs:
  build:
    docker:
      - image: node:10-alpine
      - image: mongo:4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Running Lint Checks
          command: npm run lint
      - run:
          name: Running Unit Tests
          command: npm run test:unit
      - run:
          name: Running Integration Tests
          command: npm run test:integration
workflows:
  version: 2
  build:
    jobs:
      - build
